# Generated by Django 5.1.3 on 2025-03-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0002_alter_photo_experience_alter_photo_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
