# Generated by Django 5.1.3 on 2024-12-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0002_rename_chat_room_message_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="direct_messages.chatroom",
            ),
        ),
    ]
